name: SuperHolidayGift
version: 1.0-SNAPSHOT
main: com.piaofu.owner.superholidaygift.SuperHolidayGift
api-version: 1.13
depend: [VexView]
authors: [PiaoFu]
description: This is a plugin what is holiday gift for server
